stockexchange/stockexchange/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:band_id>', views.band_detail, name='band-detail'),
    path('about-us/', views.about),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:listing_id>', views.listing_detail, name='listing-detail'),
    path('contact-us/', views.contact),
]

stockexchange/listings/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        JAZZ = 'JZ'

    def __str__(self):
        return self.name

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5, default='HH')
    biography = models.fields.CharField(max_length=1000, default='')
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2024)],
        default=2000)
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)


class Listing(models.Model):
    class Type(models.TextChoices):
        RECORDS = 'REC'
        CLOTHING = 'CLO'
        POSTERS = 'POST'
        MISCELLANEOUS = 'MIS'

    def __str__(self):
        return f'{self.title}'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2024)],
                                      blank=True, null=True)
    type = models.fields.CharField(choices=Type.choices, max_length=5, default='REC')

    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

stockexchange/listings/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from listings.models import Band, Listing


def band_list(request):
    bands = Band.objects.all()
    return render(request, "listings/band_list.html",
                  {'bands': bands})


def band_detail(request, band_id):
    # band = Band.objects.get(id=band_id)
    band = get_object_or_404(Band, id=band_id)
    return render(request, "listings/band_detail.html",
                  {'band': band})


def about(request):
    return render(request, 'listings/about.html')


def listing_list(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listing_list.html',
                  {'listings': listings})


def listing_detail(request, listing_id):
    # band = Band.objects.get(id=band_id)
    listing = get_object_or_404(Listing, id=listing_id)
    return render(request, "listings/listing_detail.html",
                  {'listing': listing})


def contact(request):
    return render(request, 'listings/contact.html')

stockexchange/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

    {% block content %}
    <h1> A propos</h1>
    <p>Nous aimons la bourse de marchandises</p>
    {% endblock %}

stockexchange/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1> Bienvenue sur la page du groupe {{band.name}}</h1>
    <ul>
        <li> L'identifiant est {{band.id}}</li>
        <li> Le genre est  {{band.get_genre_display}}</li>
        <li> Le groupe est-il actif ==>  {{band.active|yesno}}</li>
        <li> Il a été créé en {{band.year_formed}}</li>
        {% if band.official_homepage %}
            <li>Son site internet est <a href="https://foofighters.com/"> {{band.official_homepage}}</a> </li>
        {% endif %}

    </ul>


    {% if band.listing_set.all %}
    <p>
    Il a été annoncé par:
            {% for listing in band.listing_set.all %}
            <li>
                {{ listing.title }}
            </li>
            {% endfor %}
     </p>
    {% endif %}


    <p> {{ band.biography }} </p>

    <h3>Retour aux <a href="{% url 'band-list' %}">groupes</a> </h3>
{% endblock %}

stockexchange/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

      <h1> Groupes</h1>
        <p> J'ai {{ bands|length }} groupes préférés qui sont: </p>

        <ul>
            {% for band in bands %}
                <li>
                    <a href="{% url 'band-detail' band.id %}"> {{band.name}} </a>
                </li>
            {% endfor %}
        </ul>

{% endblock %}

stockexchange/listings/templates/listings/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>stockexchange</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
</head>
<body>
        <nav>
            <ul>
                <li> <a href="{% url 'band-list' %}"> Groupes</a> </li>
                <li> <a href="{% url 'listing-list' %}"> Annonces</a> </li>
            </ul>
        </nav>
        {% block content %}{% endblock %}
</body>
</html>

stockexchange/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

    {% block content %}
    <h1> Nous contacter</h1>
    <p>Vous pouvez nous joindre via .... </p>
    {% endblock %}

stockexchange/listings/templates/listings/hello.html
{% extends 'listings/base.html' %}

{% block content %}

      <h1> Hello Django !</h1>
        <p> J'ai {{ bands|length }} groupes préférés qui sont: </p>

        <ul>
            {% for band in bands %}
                <li>
                    {{band.name|upper}}
                </li>
            {% endfor %}
        </ul>

{% endblock %}

stockexchange/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>
        Bienvenue sur la page du groupe
    </h1>
     <h3>
            {{ listing.title}}
     </h3>
    <ul>
        <li> L'identifiant est {{listing.id}} </li>
        <li> Le type est  {{listing.type}} </li>

        {% if listing.year %}
        <li> Il a été créé en {{listing.year}} </li>
        {% endif %}

        <li> Cette annonce est relative au groupe {{listing.band}} </li>
    </ul>

    <h3>Retour aux <a href="{% url 'listing-list' %}">annonces</a> </h3>
{% endblock %}

stockexchange/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

    {% block content %}
    <h1> Ci-après les grands titres pour nos annonces</h1>
            <ul>
                {% for listing in listings %}
                <li> <a href="{% url 'listing-detail' listing.id %}"> {{ listing.title }} </a> </li>
                {% endfor %}
            </ul>
    {% endblock %}

stockexchange/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

    {% block content %}
    <h1> Ci-après les grands titres pour nos annonces</h1>
            <ul>
                {% for listing in listings %}
                <li> {{ listing.title }}</li>
                {% endfor %}
            </ul>
    {% endblock %}